import type { AggregateModel } from "./calculations/jamb";

export type CourseCutoff = {
  course: string;
  /** Illustrative departmental UTME cutoff (not official) */
  utmeMin: number;
  /** Illustrative aggregate target out of 100 */
  aggregateHint?: number;
};

export type University = {
  slug: string;
  name: string;
  shortName: string;
  model: AggregateModel;
  note: string;
  state: string;
  seoNote: string;
  /** School-wide / general UTME cutoff often published for screening eligibility */
  generalUtmeCutoff: number;
  /** Sample competitive courses — illustrative only, change yearly */
  courseCutoffs: CourseCutoff[];
};

/**
 * Top Nigerian universities — aggregate models & cutoffs are common patterns for planning.
 * Official cut-offs change every admission year; always verify with the school / JAMB CAPS.
 */
export const universities: University[] = [
  {
    slug: "unilag",
    name: "University of Lagos",
    shortName: "UNILAG",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Lagos",
    seoNote: "Estimate UNILAG aggregate from UTME and Post-UTME.",
    generalUtmeCutoff: 200,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 280, aggregateHint: 78 },
      { course: "Law", utmeMin: 270, aggregateHint: 74 },
      { course: "Accounting", utmeMin: 240, aggregateHint: 68 },
      { course: "Computer Science", utmeMin: 250, aggregateHint: 70 },
      { course: "Mass Communication", utmeMin: 240, aggregateHint: 68 },
    ],
  },
  {
    slug: "ui",
    name: "University of Ibadan",
    shortName: "UI",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Oyo",
    seoNote: "UI aggregate calculator using common 50:50 weighting.",
    generalUtmeCutoff: 200,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 280, aggregateHint: 78 },
      { course: "Law", utmeMin: 260, aggregateHint: 72 },
      { course: "Pharmacy", utmeMin: 270, aggregateHint: 74 },
      { course: "Economics", utmeMin: 230, aggregateHint: 65 },
      { course: "Computer Science", utmeMin: 240, aggregateHint: 68 },
    ],
  },
  {
    slug: "oau",
    name: "Obafemi Awolowo University",
    shortName: "OAU",
    model: "40-60",
    note: "JAMB 40% + Post-UTME 60%",
    state: "Osun",
    seoNote: "OAU Ile-Ife style aggregate estimate.",
    generalUtmeCutoff: 200,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 280, aggregateHint: 75 },
      { course: "Law", utmeMin: 260, aggregateHint: 70 },
      { course: "Pharmacy", utmeMin: 270, aggregateHint: 72 },
      { course: "Electrical Engineering", utmeMin: 240, aggregateHint: 65 },
      { course: "Computer Science", utmeMin: 240, aggregateHint: 66 },
    ],
  },
  {
    slug: "abu",
    name: "Ahmadu Bello University",
    shortName: "ABU",
    model: "40-60",
    note: "JAMB 40% + Post-UTME 60%",
    state: "Kaduna",
    seoNote: "ABU Zaria aggregate from UTME and screening.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 260, aggregateHint: 72 },
      { course: "Law", utmeMin: 240, aggregateHint: 66 },
      { course: "Accounting", utmeMin: 220, aggregateHint: 60 },
      { course: "Computer Science", utmeMin: 220, aggregateHint: 62 },
      { course: "Civil Engineering", utmeMin: 220, aggregateHint: 60 },
    ],
  },
  {
    slug: "unn",
    name: "University of Nigeria, Nsukka",
    shortName: "UNN",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Enugu",
    seoNote: "UNN aggregate calculator for admission planning.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 270, aggregateHint: 74 },
      { course: "Law", utmeMin: 250, aggregateHint: 68 },
      { course: "Pharmacy", utmeMin: 260, aggregateHint: 70 },
      { course: "Mass Communication", utmeMin: 220, aggregateHint: 62 },
      { course: "Computer Science", utmeMin: 230, aggregateHint: 64 },
    ],
  },
  {
    slug: "uniben",
    name: "University of Benin",
    shortName: "UNIBEN",
    model: "40-60",
    note: "JAMB 40% + Post-UTME 60%",
    state: "Edo",
    seoNote: "UNIBEN aggregate estimate (common 40:60 pattern).",
    generalUtmeCutoff: 200,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 270, aggregateHint: 74 },
      { course: "Law", utmeMin: 250, aggregateHint: 68 },
      { course: "Pharmacy", utmeMin: 260, aggregateHint: 70 },
      { course: "Accounting", utmeMin: 220, aggregateHint: 60 },
      { course: "Computer Science", utmeMin: 230, aggregateHint: 64 },
    ],
  },
  {
    slug: "unilorin",
    name: "University of Ilorin",
    shortName: "UNILORIN",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Kwara",
    seoNote: "UNILORIN aggregate calculator.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 270, aggregateHint: 74 },
      { course: "Law", utmeMin: 250, aggregateHint: 68 },
      { course: "Nursing", utmeMin: 240, aggregateHint: 66 },
      { course: "Accounting", utmeMin: 220, aggregateHint: 60 },
      { course: "Computer Science", utmeMin: 230, aggregateHint: 64 },
    ],
  },
  {
    slug: "uniport",
    name: "University of Port Harcourt",
    shortName: "UNIPORT",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Rivers",
    seoNote: "UNIPORT aggregate from JAMB and Post-UTME.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 260, aggregateHint: 72 },
      { course: "Petroleum Engineering", utmeMin: 240, aggregateHint: 66 },
      { course: "Law", utmeMin: 240, aggregateHint: 66 },
      { course: "Accounting", utmeMin: 210, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 220, aggregateHint: 62 },
    ],
  },
  {
    slug: "unical",
    name: "University of Calabar",
    shortName: "UNICAL",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Cross River",
    seoNote: "UNICAL admission aggregate estimate.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 70 },
      { course: "Law", utmeMin: 230, aggregateHint: 64 },
      { course: "Nursing", utmeMin: 220, aggregateHint: 62 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 210, aggregateHint: 58 },
    ],
  },
  {
    slug: "unijos",
    name: "University of Jos",
    shortName: "UNIJOS",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Plateau",
    seoNote: "UNIJOS aggregate calculator.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 70 },
      { course: "Law", utmeMin: 230, aggregateHint: 64 },
      { course: "Pharmacy", utmeMin: 240, aggregateHint: 66 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 210, aggregateHint: 58 },
    ],
  },
  {
    slug: "uniabuja",
    name: "University of Abuja",
    shortName: "UNIABUJA",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "FCT",
    seoNote: "University of Abuja aggregate estimate.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 70 },
      { course: "Law", utmeMin: 230, aggregateHint: 64 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 210, aggregateHint: 58 },
      { course: "Political Science", utmeMin: 190, aggregateHint: 54 },
    ],
  },
  {
    slug: "unimaid",
    name: "University of Maiduguri",
    shortName: "UNIMAID",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Borno",
    seoNote: "UNIMAID aggregate calculator.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 240, aggregateHint: 68 },
      { course: "Law", utmeMin: 220, aggregateHint: 60 },
      { course: "Pharmacy", utmeMin: 230, aggregateHint: 64 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 54 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 56 },
    ],
  },
  {
    slug: "noun",
    name: "National Open University of Nigeria",
    shortName: "NOUN",
    model: "50-50",
    note: "JAMB / screening style (illustrative)",
    state: "FCT",
    seoNote: "NOUN-related aggregate planning tool.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Law", utmeMin: 200, aggregateHint: 55 },
      { course: "Business Administration", utmeMin: 180, aggregateHint: 50 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 52 },
      { course: "Education courses", utmeMin: 160, aggregateHint: 48 },
      { course: "Mass Communication", utmeMin: 180, aggregateHint: 50 },
    ],
  },
  {
    slug: "lasu",
    name: "Lagos State University",
    shortName: "LASU",
    model: "40-60",
    note: "JAMB 40% + Post-UTME 60%",
    state: "Lagos",
    seoNote: "LASU aggregate calculator for Lagos State University.",
    generalUtmeCutoff: 190,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 270, aggregateHint: 74 },
      { course: "Law", utmeMin: 250, aggregateHint: 68 },
      { course: "Accounting", utmeMin: 220, aggregateHint: 60 },
      { course: "Mass Communication", utmeMin: 220, aggregateHint: 62 },
      { course: "Computer Science", utmeMin: 230, aggregateHint: 64 },
    ],
  },
  {
    slug: "lasustech",
    name: "Lagos State University of Science and Technology",
    shortName: "LASUSTECH",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Lagos",
    seoNote: "LASUSTECH aggregate estimate.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 220, aggregateHint: 62 },
      { course: "Engineering (general)", utmeMin: 200, aggregateHint: 58 },
      { course: "Architecture", utmeMin: 210, aggregateHint: 60 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 54 },
      { course: "Science courses", utmeMin: 180, aggregateHint: 52 },
    ],
  },
  {
    slug: "futa",
    name: "Federal University of Technology, Akure",
    shortName: "FUTA",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Ondo",
    seoNote: "FUTA aggregate calculator.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 230, aggregateHint: 64 },
      { course: "Electrical Engineering", utmeMin: 220, aggregateHint: 62 },
      { course: "Mechanical Engineering", utmeMin: 210, aggregateHint: 60 },
      { course: "Architecture", utmeMin: 210, aggregateHint: 60 },
      { course: "Industrial Chemistry", utmeMin: 190, aggregateHint: 54 },
    ],
  },
  {
    slug: "futminna",
    name: "Federal University of Technology, Minna",
    shortName: "FUTMinna",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Niger",
    seoNote: "FUT Minna aggregate estimate.",
    generalUtmeCutoff: 170,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 210, aggregateHint: 60 },
      { course: "Electrical Engineering", utmeMin: 200, aggregateHint: 58 },
      { course: "Civil Engineering", utmeMin: 200, aggregateHint: 56 },
      { course: "Architecture", utmeMin: 200, aggregateHint: 58 },
      { course: "Cyber Security", utmeMin: 210, aggregateHint: 60 },
    ],
  },
  {
    slug: "futo",
    name: "Federal University of Technology, Owerri",
    shortName: "FUTO",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Imo",
    seoNote: "FUTO aggregate calculator.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 220, aggregateHint: 62 },
      { course: "Electrical Engineering", utmeMin: 210, aggregateHint: 60 },
      { course: "Mechanical Engineering", utmeMin: 200, aggregateHint: 58 },
      { course: "Petroleum Engineering", utmeMin: 210, aggregateHint: 60 },
      { course: "Architecture", utmeMin: 200, aggregateHint: 58 },
    ],
  },
  {
    slug: "buk",
    name: "Bayero University Kano",
    shortName: "BUK",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Kano",
    seoNote: "BUK aggregate from UTME and Post-UTME.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 70 },
      { course: "Law", utmeMin: 230, aggregateHint: 64 },
      { course: "Pharmacy", utmeMin: 240, aggregateHint: 66 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 210, aggregateHint: 58 },
    ],
  },
  {
    slug: "udusok",
    name: "Usmanu Danfodiyo University",
    shortName: "UDUSOK",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Sokoto",
    seoNote: "UDUSOK aggregate calculator.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 240, aggregateHint: 68 },
      { course: "Law", utmeMin: 220, aggregateHint: 60 },
      { course: "Pharmacy", utmeMin: 230, aggregateHint: 64 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 54 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 56 },
    ],
  },
  {
    slug: "unizik",
    name: "Nnamdi Azikiwe University",
    shortName: "UNIZIK",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Anambra",
    seoNote: "UNIZIK (NAU) aggregate estimate.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 260, aggregateHint: 72 },
      { course: "Law", utmeMin: 240, aggregateHint: 66 },
      { course: "Pharmacy", utmeMin: 250, aggregateHint: 68 },
      { course: "Mass Communication", utmeMin: 210, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 220, aggregateHint: 62 },
    ],
  },
  {
    slug: "fuoye",
    name: "Federal University Oye-Ekiti",
    shortName: "FUOYE",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Ekiti",
    seoNote: "FUOYE aggregate calculator.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 70 },
      { course: "Law", utmeMin: 230, aggregateHint: 64 },
      { course: "Nursing", utmeMin: 220, aggregateHint: 62 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 56 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 54 },
    ],
  },
  {
    slug: "funaab",
    name: "Federal University of Agriculture, Abeokuta",
    shortName: "FUNAAB",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Ogun",
    seoNote: "FUNAAB aggregate estimate.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Veterinary Medicine", utmeMin: 220, aggregateHint: 62 },
      { course: "Agriculture (general)", utmeMin: 180, aggregateHint: 52 },
      { course: "Food Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 56 },
      { course: "Mechanical Engineering", utmeMin: 200, aggregateHint: 56 },
    ],
  },
  {
    slug: "mouau",
    name: "Michael Okpara University of Agriculture",
    shortName: "MOUAU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Abia",
    seoNote: "MOUAU aggregate calculator.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Veterinary Medicine", utmeMin: 210, aggregateHint: 60 },
      { course: "Agriculture", utmeMin: 170, aggregateHint: 50 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Engineering", utmeMin: 190, aggregateHint: 54 },
      { course: "Food Science", utmeMin: 180, aggregateHint: 52 },
    ],
  },
  {
    slug: "delstu",
    name: "Delta State University",
    shortName: "DELSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Delta",
    seoNote: "DELSU aggregate calculator.",
    generalUtmeCutoff: 170,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 70 },
      { course: "Law", utmeMin: 230, aggregateHint: 64 },
      { course: "Nursing", utmeMin: 220, aggregateHint: 62 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 56 },
      { course: "Mass Communication", utmeMin: 200, aggregateHint: 56 },
    ],
  },
  {
    slug: "rsu",
    name: "Rivers State University",
    shortName: "RSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Rivers",
    seoNote: "RSU aggregate estimate.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 70 },
      { course: "Law", utmeMin: 230, aggregateHint: 64 },
      { course: "Engineering", utmeMin: 200, aggregateHint: 58 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 210, aggregateHint: 58 },
    ],
  },
  {
    slug: "eksu",
    name: "Ekiti State University",
    shortName: "EKSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Ekiti",
    seoNote: "EKSU aggregate calculator.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 240, aggregateHint: 68 },
      { course: "Law", utmeMin: 220, aggregateHint: 62 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 60 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 54 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 56 },
    ],
  },
  {
    slug: "ksu",
    name: "Kogi State University",
    shortName: "KSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Kogi",
    seoNote: "KSU Anyigba aggregate estimate.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Law", utmeMin: 220, aggregateHint: 60 },
      { course: "Medicine-related", utmeMin: 230, aggregateHint: 64 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 52 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Mass Communication", utmeMin: 180, aggregateHint: 52 },
    ],
  },
  {
    slug: "covenant",
    name: "Covenant University",
    shortName: "Covenant",
    model: "50-30-20",
    note: "JAMB + screening + O'Level style (illustrative)",
    state: "Ogun",
    seoNote: "Covenant University aggregate planning tool.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 220, aggregateHint: 65 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 60 },
      { course: "Engineering", utmeMin: 210, aggregateHint: 62 },
      { course: "Architecture", utmeMin: 200, aggregateHint: 60 },
      { course: "Mass Communication", utmeMin: 200, aggregateHint: 58 },
    ],
  },
  {
    slug: "babcock",
    name: "Babcock University",
    shortName: "Babcock",
    model: "50-30-20",
    note: "JAMB + screening + O'Level style (illustrative)",
    state: "Ogun",
    seoNote: "Babcock University aggregate estimate.",
    generalUtmeCutoff: 170,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 240, aggregateHint: 70 },
      { course: "Law", utmeMin: 220, aggregateHint: 64 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 62 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 58 },
    ],
  },
];

export const universityMap = Object.fromEntries(universities.map((u) => [u.slug, u]));

export function getUniversity(slug: string) {
  return universityMap[slug] ?? null;
}
