import type { AggregateModel } from "./calculations/jamb";

export type CourseCutoff = {
  course: string;
  utmeMin: number;
  aggregateHint?: number;
};

export type University = {
  slug: string;
  name: string;
  shortName: string;
  model: AggregateModel;
  note: string;
  state: string;
  seoNote: string;
  generalUtmeCutoff: number;
  courseCutoffs: CourseCutoff[];
};

/**
 * Nigerian universities — aggregate models & cut-offs are illustrative planning guides.
 * Official figures change every admission year; verify with JAMB CAPS and each school.
 */
export const universities: University[] = [
  {
    slug: "unilag",
    name: "University of Lagos",
    shortName: "UNILAG",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Lagos",
    seoNote: "UNILAG aggregate and cut-off guide.",
    generalUtmeCutoff: 200,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 280, aggregateHint: 83 },
      { course: "Law", utmeMin: 260, aggregateHint: 79 },
      { course: "Computer Science", utmeMin: 250, aggregateHint: 82 },
      { course: "Accounting", utmeMin: 240, aggregateHint: 68 },
      { course: "Mass Communication", utmeMin: 240, aggregateHint: 74 },
      { course: "Nursing", utmeMin: 260, aggregateHint: 77 },
      { course: "Pharmacy", utmeMin: 250, aggregateHint: 78 },
      { course: "Engineering (general)", utmeMin: 250, aggregateHint: 75 },
    ],
  
  },
  {
    slug: "ui",
    name: "University of Ibadan",
    shortName: "UI",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Oyo",
    seoNote: "UI aggregate and cut-off guide.",
    generalUtmeCutoff: 200,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 280, aggregateHint: 78 },
      { course: "Law", utmeMin: 250, aggregateHint: 72 },
      { course: "Pharmacy", utmeMin: 260, aggregateHint: 74 },
      { course: "Computer Science", utmeMin: 240, aggregateHint: 68 },
      { course: "Economics", utmeMin: 230, aggregateHint: 65 },
    ],
  },
  {
    slug: "oau",
    name: "Obafemi Awolowo University",
    shortName: "OAU",
    model: "40-60",
    note: "JAMB 40% + Post-UTME 60%",
    state: "Osun",
    seoNote: "OAU aggregate and cut-off guide.",
    generalUtmeCutoff: 200,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 270, aggregateHint: 76 },
      { course: "Law", utmeMin: 250, aggregateHint: 72 },
      { course: "Pharmacy", utmeMin: 260, aggregateHint: 74 },
      { course: "Computer Science", utmeMin: 240, aggregateHint: 66 },
      { course: "Electrical Engineering", utmeMin: 240, aggregateHint: 65 },
    ],
  },
  {
    slug: "abu",
    name: "Ahmadu Bello University",
    shortName: "ABU",
    model: "40-60",
    note: "JAMB 40% + Post-UTME 60%",
    state: "Kaduna",
    seoNote: "ABU Zaria aggregate and cut-off guide.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 260, aggregateHint: 68 },
      { course: "Law", utmeMin: 240, aggregateHint: 62 },
      { course: "Computer Science", utmeMin: 220, aggregateHint: 58 },
      { course: "Accounting", utmeMin: 220, aggregateHint: 55 },
      { course: "Engineering (general)", utmeMin: 220, aggregateHint: 56 }
    ],
  },
  {
    slug: "unn",
    name: "University of Nigeria, Nsukka",
    shortName: "UNN",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Enugu",
    seoNote: "UNN aggregate and cut-off guide.",
    generalUtmeCutoff: 200,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 270, aggregateHint: 68 },
      { course: "Law", utmeMin: 250, aggregateHint: 62 },
      { course: "Computer Science", utmeMin: 230, aggregateHint: 58 },
      { course: "Accounting", utmeMin: 220, aggregateHint: 55 },
      { course: "Engineering (general)", utmeMin: 230, aggregateHint: 57 }
    ],
  },
  {
    slug: "uniben",
    name: "University of Benin",
    shortName: "UNIBEN",
    model: "40-60",
    note: "JAMB 40% + Post-UTME 60%",
    state: "Edo",
    seoNote: "UNIBEN aggregate and cut-off guide.",
    generalUtmeCutoff: 200,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 270, aggregateHint: 68 },
      { course: "Law", utmeMin: 250, aggregateHint: 62 },
      { course: "Computer Science", utmeMin: 230, aggregateHint: 58 },
      { course: "Accounting", utmeMin: 220, aggregateHint: 55 },
      { course: "Engineering (general)", utmeMin: 230, aggregateHint: 57 }
    ],
  },
  {
    slug: "unilorin",
    name: "University of Ilorin",
    shortName: "UNILORIN",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Kwara",
    seoNote: "UNILORIN aggregate and cut-off guide.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 270, aggregateHint: 68 },
      { course: "Law", utmeMin: 250, aggregateHint: 62 },
      { course: "Computer Science", utmeMin: 230, aggregateHint: 58 },
      { course: "Accounting", utmeMin: 220, aggregateHint: 55 },
      { course: "Engineering (general)", utmeMin: 220, aggregateHint: 56 }
    ],
  },
  {
    slug: "uniport",
    name: "University of Port Harcourt",
    shortName: "UNIPORT",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Rivers",
    seoNote: "UNIPORT aggregate and cut-off guide.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 260, aggregateHint: 68 },
      { course: "Law", utmeMin: 240, aggregateHint: 62 },
      { course: "Computer Science", utmeMin: 220, aggregateHint: 58 },
      { course: "Accounting", utmeMin: 210, aggregateHint: 54 },
      { course: "Engineering (general)", utmeMin: 220, aggregateHint: 56 }
    ],
  },
  {
    slug: "unical",
    name: "University of Calabar",
    shortName: "UNICAL",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Cross River",
    seoNote: "UNICAL aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 64 },
      { course: "Law", utmeMin: 230, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 220, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 210, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 50 }
    ],
  },
  {
    slug: "unijos",
    name: "University of Jos",
    shortName: "UNIJOS",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Plateau",
    seoNote: "UNIJOS aggregate and cut-off guide.",
    generalUtmeCutoff: 170,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 64 },
      { course: "Law", utmeMin: 230, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 220, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 210, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 50 }
    ],
  },
  {
    slug: "uniabuja",
    name: "University of Abuja",
    shortName: "UNIABUJA",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "FCT",
    seoNote: "UNIABUJA aggregate and cut-off guide.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 64 },
      { course: "Law", utmeMin: 230, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 210, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 50 }
    ],
  },
  {
    slug: "unimaid",
    name: "University of Maiduguri",
    shortName: "UNIMAID",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Borno",
    seoNote: "UNIMAID aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 240, aggregateHint: 64 },
      { course: "Law", utmeMin: 220, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 50 }
    ],
  },
  {
    slug: "unizik",
    name: "Nnamdi Azikiwe University",
    shortName: "UNIZIK",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Anambra",
    seoNote: "UNIZIK aggregate and cut-off guide.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 260, aggregateHint: 68 },
      { course: "Law", utmeMin: 240, aggregateHint: 62 },
      { course: "Computer Science", utmeMin: 220, aggregateHint: 58 },
      { course: "Accounting", utmeMin: 210, aggregateHint: 54 },
      { course: "Engineering (general)", utmeMin: 220, aggregateHint: 56 }
    ],
  },
  {
    slug: "buk",
    name: "Bayero University Kano",
    shortName: "BUK",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Kano",
    seoNote: "BUK aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 64 },
      { course: "Law", utmeMin: 230, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 220, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 210, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 50 }
    ],
  },
  {
    slug: "udusok",
    name: "Usmanu Danfodiyo University",
    shortName: "UDUSOK",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Sokoto",
    seoNote: "UDUSOK aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 240, aggregateHint: 64 },
      { course: "Law", utmeMin: 220, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 50 }
    ],
  },
  {
    slug: "noun",
    name: "National Open University of Nigeria",
    shortName: "NOUN",
    model: "50-50",
    note: "JAMB / screening (illustrative)",
    state: "FCT",
    seoNote: "NOUN aggregate planning guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Law", utmeMin: 200, aggregateHint: 55 },
      { course: "Business Administration", utmeMin: 180, aggregateHint: 50 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 52 },
      { course: "Education", utmeMin: 160, aggregateHint: 48 },
      { course: "Mass Communication", utmeMin: 180, aggregateHint: 50 }
    ],
  },
  {
    slug: "futa",
    name: "Federal University of Technology, Akure",
    shortName: "FUTA",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Ondo",
    seoNote: "FUTA aggregate and cut-off guide.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 230, aggregateHint: 57 },
      { course: "Electrical Engineering", utmeMin: 220, aggregateHint: 55 },
      { course: "Mechanical Engineering", utmeMin: 210, aggregateHint: 54 },
      { course: "Architecture", utmeMin: 210, aggregateHint: 54 },
      { course: "Cyber Security / ICT", utmeMin: 220, aggregateHint: 56 }
    ],
  },
  {
    slug: "futminna",
    name: "Federal University of Technology, Minna",
    shortName: "FUTMinna",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Niger",
    seoNote: "FUT Minna aggregate and cut-off guide.",
    generalUtmeCutoff: 170,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 210, aggregateHint: 56 },
      { course: "Electrical Engineering", utmeMin: 200, aggregateHint: 54 },
      { course: "Mechanical Engineering", utmeMin: 200, aggregateHint: 54 },
      { course: "Architecture", utmeMin: 200, aggregateHint: 54 },
      { course: "Cyber Security / ICT", utmeMin: 210, aggregateHint: 56 }
    ],
  },
  {
    slug: "futo",
    name: "Federal University of Technology, Owerri",
    shortName: "FUTO",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Imo",
    seoNote: "FUTO aggregate and cut-off guide.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 220, aggregateHint: 56 },
      { course: "Electrical Engineering", utmeMin: 210, aggregateHint: 54 },
      { course: "Mechanical Engineering", utmeMin: 200, aggregateHint: 54 },
      { course: "Architecture", utmeMin: 200, aggregateHint: 54 },
      { course: "Cyber Security / ICT", utmeMin: 210, aggregateHint: 56 }
    ],
  },
  {
    slug: "fuoye",
    name: "Federal University Oye-Ekiti",
    shortName: "FUOYE",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Ekiti",
    seoNote: "FUOYE aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 64 },
      { course: "Law", utmeMin: 230, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 220, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 50 }
    ],
  },
  {
    slug: "funaab",
    name: "Federal University of Agriculture, Abeokuta",
    shortName: "FUNAAB",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Ogun",
    seoNote: "FUNAAB aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Veterinary Medicine", utmeMin: 210, aggregateHint: 56 },
      { course: "Agriculture", utmeMin: 170, aggregateHint: 48 },
      { course: "Food Science", utmeMin: 180, aggregateHint: 50 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 52 },
      { course: "Engineering", utmeMin: 190, aggregateHint: 52 }
    ],
  },
  {
    slug: "mouau",
    name: "Michael Okpara University of Agriculture",
    shortName: "MOUAU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Abia",
    seoNote: "MOUAU aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Veterinary Medicine", utmeMin: 210, aggregateHint: 56 },
      { course: "Agriculture", utmeMin: 170, aggregateHint: 48 },
      { course: "Food Science", utmeMin: 180, aggregateHint: 50 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 52 },
      { course: "Engineering", utmeMin: 190, aggregateHint: 52 }
    ],
  },
  {
    slug: "fuhso",
    name: "Federal University of Health Sciences, Otukpo",
    shortName: "FUHSO",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Benue",
    seoNote: "FUHSO aggregate and cut-off guide.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 70 },
      { course: "Nursing", utmeMin: 230, aggregateHint: 64 },
      { course: "Medical Laboratory Science", utmeMin: 220, aggregateHint: 60 },
      { course: "Anatomy", utmeMin: 200, aggregateHint: 56 },
      { course: "Physiology", utmeMin: 200, aggregateHint: 56 }
    ],
  },
  {
    slug: "ful",
    name: "Federal University Lokoja",
    shortName: "FUL",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Kogi",
    seoNote: "FUL Lokoja aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 64 },
      { course: "Law", utmeMin: 210, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 50 }
    ],
  },
  {
    slug: "fuwukari",
    name: "Federal University Wukari",
    shortName: "FUWukari",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Taraba",
    seoNote: "FU Wukari aggregate and cut-off guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 64 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 50 }
    ],
  },
  {
    slug: "fud",
    name: "Federal University Dutse",
    shortName: "FUD",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Jigawa",
    seoNote: "FU Dutse aggregate and cut-off guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 64 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 50 }
    ],
  },
  {
    slug: "fugashua",
    name: "Federal University Gashua",
    shortName: "FUGashua",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Yobe",
    seoNote: "FU Gashua aggregate and cut-off guide.",
    generalUtmeCutoff: 140,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 64 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 180, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 170, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 160, aggregateHint: 50 }
    ],
  },
  {
    slug: "fugusau",
    name: "Federal University Gusau",
    shortName: "FUGusau",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Zamfara",
    seoNote: "FU Gusau aggregate and cut-off guide.",
    generalUtmeCutoff: 140,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 64 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 180, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 170, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 160, aggregateHint: 50 }
    ],
  },
  {
    slug: "fukashere",
    name: "Federal University Kashere",
    shortName: "FUKashere",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Gombe",
    seoNote: "FU Kashere aggregate and cut-off guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 64 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 50 }
    ],
  },
  {
    slug: "fulafia",
    name: "Federal University of Lafia",
    shortName: "FULafia",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Nasarawa",
    seoNote: "FU Lafia aggregate and cut-off guide.",
    generalUtmeCutoff: 170,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 64 },
      { course: "Law", utmeMin: 210, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 50 }
    ],
  },
  {
    slug: "fuotuoke",
    name: "Federal University Otuoke",
    shortName: "FUOtuoke",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Bayelsa",
    seoNote: "FU Otuoke aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 64 },
      { course: "Law", utmeMin: 210, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 50 }
    ],
  },
  {
    slug: "fupre",
    name: "Federal University of Petroleum Resources",
    shortName: "FUPRE",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Delta",
    seoNote: "FUPRE Effurun aggregate and cut-off guide.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Petroleum Engineering", utmeMin: 220, aggregateHint: 62 },
      { course: "Chemical Engineering", utmeMin: 210, aggregateHint: 60 },
      { course: "Computer Science", utmeMin: 210, aggregateHint: 58 },
      { course: "Mechanical Engineering", utmeMin: 200, aggregateHint: 56 },
      { course: "Electrical Engineering", utmeMin: 200, aggregateHint: 56 }
    ],
  },
  {
    slug: "atbu",
    name: "Abubakar Tafawa Balewa University",
    shortName: "ATBU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Bauchi",
    seoNote: "ATBU Bauchi aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 210, aggregateHint: 56 },
      { course: "Electrical Engineering", utmeMin: 200, aggregateHint: 54 },
      { course: "Mechanical Engineering", utmeMin: 200, aggregateHint: 54 },
      { course: "Architecture", utmeMin: 190, aggregateHint: 54 },
      { course: "Cyber Security / ICT", utmeMin: 200, aggregateHint: 56 }
    ],
  },
  {
    slug: "mau",
    name: "Modibbo Adama University",
    shortName: "MAU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Adamawa",
    seoNote: "MAU Yola aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 210, aggregateHint: 56 },
      { course: "Electrical Engineering", utmeMin: 200, aggregateHint: 54 },
      { course: "Mechanical Engineering", utmeMin: 200, aggregateHint: 54 },
      { course: "Architecture", utmeMin: 190, aggregateHint: 54 },
      { course: "Cyber Security / ICT", utmeMin: 200, aggregateHint: 56 }
    ],
  },
  {
    slug: "nda",
    name: "Nigerian Defence Academy",
    shortName: "NDA",
    model: "50-50",
    note: "JAMB + NDA screening (illustrative)",
    state: "Kaduna",
    seoNote: "NDA Kaduna aggregate planning guide.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Engineering", utmeMin: 210, aggregateHint: 60 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 58 },
      { course: "Sciences", utmeMin: 190, aggregateHint: 54 },
      { course: "Arts / Social Sciences", utmeMin: 180, aggregateHint: 52 },
      { course: "Military studies path", utmeMin: 180, aggregateHint: 52 }
    ],
  },
  {
    slug: "police-academy",
    name: "Nigeria Police Academy",
    shortName: "POLAC",
    model: "50-50",
    note: "JAMB + academy screening (illustrative)",
    state: "Kano",
    seoNote: "Police Academy Wudil cut-off guide.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Social Sciences", utmeMin: 180, aggregateHint: 52 },
      { course: "Sciences", utmeMin: 180, aggregateHint: 52 },
      { course: "Law-related", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 50 }
    ],
  },
  {
    slug: "lasu",
    name: "Lagos State University",
    shortName: "LASU",
    model: "40-60",
    note: "JAMB 40% + Post-UTME 60%",
    state: "Lagos",
    seoNote: "LASU aggregate and cut-off guide.",
    generalUtmeCutoff: 195,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 270, aggregateHint: 68 },
      { course: "Law", utmeMin: 250, aggregateHint: 62 },
      { course: "Computer Science", utmeMin: 230, aggregateHint: 58 },
      { course: "Accounting", utmeMin: 220, aggregateHint: 55 },
      { course: "Engineering (general)", utmeMin: 220, aggregateHint: 56 }
    ],
  },
  {
    slug: "lasustech",
    name: "Lagos State University of Science and Technology",
    shortName: "LASUSTECH",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Lagos",
    seoNote: "LASUSTECH aggregate and cut-off guide.",
    generalUtmeCutoff: 195,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 220, aggregateHint: 56 },
      { course: "Electrical Engineering", utmeMin: 200, aggregateHint: 54 },
      { course: "Mechanical Engineering", utmeMin: 200, aggregateHint: 54 },
      { course: "Architecture", utmeMin: 210, aggregateHint: 54 },
      { course: "Cyber Security / ICT", utmeMin: 210, aggregateHint: 56 }
    ],
  },
  {
    slug: "delstu",
    name: "Delta State University",
    shortName: "DELSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Delta",
    seoNote: "DELSU Abraka aggregate and cut-off guide.",
    generalUtmeCutoff: 170,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 64 },
      { course: "Law", utmeMin: 230, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 220, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 50 }
    ],
  },
  {
    slug: "rsu",
    name: "Rivers State University",
    shortName: "RSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Rivers",
    seoNote: "RSU aggregate and cut-off guide.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 64 },
      { course: "Law", utmeMin: 230, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 210, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 50 }
    ],
  },
  {
    slug: "eksu",
    name: "Ekiti State University",
    shortName: "EKSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Ekiti",
    seoNote: "EKSU aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 240, aggregateHint: 64 },
      { course: "Law", utmeMin: 220, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 50 }
    ],
  },
  {
    slug: "ksu",
    name: "Kogi State University",
    shortName: "KSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Kogi",
    seoNote: "KSU Anyigba aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 64 },
      { course: "Law", utmeMin: 220, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 50 }
    ],
  },
  {
    slug: "oou",
    name: "Olabisi Onabanjo University",
    shortName: "OOU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Ogun",
    seoNote: "OOU Ago-Iwoye aggregate and cut-off guide.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 64 },
      { course: "Law", utmeMin: 230, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 220, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 210, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 50 }
    ],
  },
  {
    slug: "tasued",
    name: "Tai Solarin University of Education",
    shortName: "TASUED",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Ogun",
    seoNote: "TASUED Ijagun aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Education (Science)", utmeMin: 180, aggregateHint: 52 },
      { course: "Education (Arts)", utmeMin: 170, aggregateHint: 50 },
      { course: "Vocational Education", utmeMin: 160, aggregateHint: 48 },
      { course: "Computer Science Education", utmeMin: 180, aggregateHint: 52 },
      { course: "Guidance & Counselling", utmeMin: 170, aggregateHint: 50 }
    ],
  },
  {
    slug: "aasued",
    name: "Adekunle Ajasin University",
    shortName: "AAUA",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Ondo",
    seoNote: "AAUA Akungba aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 64 },
      { course: "Law", utmeMin: 210, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 50 }
    ],
  },
  {
    slug: "uniosun",
    name: "Osun State University",
    shortName: "UNIOSUN",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Osun",
    seoNote: "UNIOSUN aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 240, aggregateHint: 64 },
      { course: "Law", utmeMin: 220, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 50 }
    ],
  },
  {
    slug: "kwasu",
    name: "Kwara State University",
    shortName: "KWASU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Kwara",
    seoNote: "KWASU Malete aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 64 },
      { course: "Law", utmeMin: 210, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 50 }
    ],
  },
  {
    slug: "imsui",
    name: "Imo State University",
    shortName: "IMSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Imo",
    seoNote: "IMSU Owerri aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 240, aggregateHint: 64 },
      { course: "Law", utmeMin: 220, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 50 }
    ],
  },
  {
    slug: "absu",
    name: "Abia State University",
    shortName: "ABSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Abia",
    seoNote: "ABSU Uturu aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 64 },
      { course: "Law", utmeMin: 210, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 50 }
    ],
  },
  {
    slug: "esut",
    name: "Enugu State University of Science and Technology",
    shortName: "ESUT",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Enugu",
    seoNote: "ESUT aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 210, aggregateHint: 56 },
      { course: "Electrical Engineering", utmeMin: 200, aggregateHint: 54 },
      { course: "Mechanical Engineering", utmeMin: 200, aggregateHint: 54 },
      { course: "Architecture", utmeMin: 190, aggregateHint: 54 },
      { course: "Cyber Security / ICT", utmeMin: 200, aggregateHint: 56 }
    ],
  },
  {
    slug: "anssu",
    name: "Chukwuemeka Odumegwu Ojukwu University",
    shortName: "COOU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Anambra",
    seoNote: "COOU (formerly ANSU) aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 64 },
      { course: "Law", utmeMin: 210, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 50 }
    ],
  },
  {
    slug: "ebsu",
    name: "Ebonyi State University",
    shortName: "EBSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Ebonyi",
    seoNote: "EBSU Abakaliki aggregate and cut-off guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 64 },
      { course: "Law", utmeMin: 210, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 50 }
    ],
  },
  {
    slug: "aksu",
    name: "Akwa Ibom State University",
    shortName: "AKSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Akwa Ibom",
    seoNote: "AKSU aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 64 },
      { course: "Law", utmeMin: 210, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 50 }
    ],
  },
  {
    slug: "crutech",
    name: "Cross River University of Technology",
    shortName: "CRUTECH",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Cross River",
    seoNote: "CRUTECH aggregate and cut-off guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 200, aggregateHint: 56 },
      { course: "Electrical Engineering", utmeMin: 190, aggregateHint: 54 },
      { course: "Mechanical Engineering", utmeMin: 190, aggregateHint: 54 },
      { course: "Architecture", utmeMin: 180, aggregateHint: 54 },
      { course: "Cyber Security / ICT", utmeMin: 190, aggregateHint: 56 }
    ],
  },
  {
    slug: "bsu",
    name: "Benue State University",
    shortName: "BSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Benue",
    seoNote: "BSU Makurdi aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 240, aggregateHint: 64 },
      { course: "Law", utmeMin: 220, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 50 }
    ],
  },
  {
    slug: "plasu",
    name: "Plateau State University",
    shortName: "PLASU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Plateau",
    seoNote: "PLASU Bokkos aggregate and cut-off guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 64 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 50 }
    ],
  },
  {
    slug: "nsuk",
    name: "Nasarawa State University",
    shortName: "NSUK",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Nasarawa",
    seoNote: "NSUK Keffi aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 64 },
      { course: "Law", utmeMin: 210, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 50 }
    ],
  },
  {
    slug: "kust",
    name: "Kano University of Science and Technology",
    shortName: "KUST",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Kano",
    seoNote: "KUST Wudil aggregate and cut-off guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 200, aggregateHint: 56 },
      { course: "Electrical Engineering", utmeMin: 190, aggregateHint: 54 },
      { course: "Mechanical Engineering", utmeMin: 190, aggregateHint: 54 },
      { course: "Architecture", utmeMin: 180, aggregateHint: 54 },
      { course: "Cyber Security / ICT", utmeMin: 190, aggregateHint: 56 }
    ],
  },
  {
    slug: "umyu",
    name: "Umaru Musa Yar'adua University",
    shortName: "UMYU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Katsina",
    seoNote: "UMYU Katsina aggregate and cut-off guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 64 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 50 }
    ],
  },
  {
    slug: "ssu",
    name: "Sokoto State University",
    shortName: "SSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Sokoto",
    seoNote: "SSU aggregate and cut-off guide.",
    generalUtmeCutoff: 140,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 64 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 180, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 170, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 160, aggregateHint: 50 }
    ],
  },
  {
    slug: "ysu",
    name: "Yobe State University",
    shortName: "YSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Yobe",
    seoNote: "YSU Damaturu aggregate and cut-off guide.",
    generalUtmeCutoff: 140,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 64 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 180, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 170, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 160, aggregateHint: 50 }
    ],
  },
  {
    slug: "gssu",
    name: "Gombe State University",
    shortName: "GSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Gombe",
    seoNote: "GSU aggregate and cut-off guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 64 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 50 }
    ],
  },
  {
    slug: "tasu",
    name: "Taraba State University",
    shortName: "TASU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Taraba",
    seoNote: "TASU Jalingo aggregate and cut-off guide.",
    generalUtmeCutoff: 140,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 64 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 180, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 170, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 160, aggregateHint: 50 }
    ],
  },
  {
    slug: "adsu",
    name: "Adamawa State University",
    shortName: "ADSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Adamawa",
    seoNote: "ADSU Mubi aggregate and cut-off guide.",
    generalUtmeCutoff: 140,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 64 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 180, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 170, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 160, aggregateHint: 50 }
    ],
  },
  {
    slug: "basug",
    name: "Bauchi State University",
    shortName: "BASUG",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Bauchi",
    seoNote: "BASUG Gadau aggregate and cut-off guide.",
    generalUtmeCutoff: 140,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 64 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 180, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 170, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 160, aggregateHint: 50 }
    ],
  },
  {
    slug: "slu",
    name: "Sule Lamido University",
    shortName: "SLU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Jigawa",
    seoNote: "SLU Kafin Hausa aggregate and cut-off guide.",
    generalUtmeCutoff: 140,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 200, aggregateHint: 64 },
      { course: "Law", utmeMin: 180, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 170, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 160, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 150, aggregateHint: 50 }
    ],
  },
  {
    slug: "ksusta",
    name: "Kebbi State University of Science and Technology",
    shortName: "KSUSTA",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Kebbi",
    seoNote: "KSUSTA Aliero aggregate and cut-off guide.",
    generalUtmeCutoff: 140,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 190, aggregateHint: 56 },
      { course: "Electrical Engineering", utmeMin: 180, aggregateHint: 54 },
      { course: "Mechanical Engineering", utmeMin: 180, aggregateHint: 54 },
      { course: "Architecture", utmeMin: 170, aggregateHint: 54 },
      { course: "Cyber Security / ICT", utmeMin: 180, aggregateHint: 56 }
    ],
  },
  {
    slug: "ysuzak",
    name: "Zamfara State University",
    shortName: "ZMSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Zamfara",
    seoNote: "Zamfara State University aggregate and cut-off guide.",
    generalUtmeCutoff: 140,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 200, aggregateHint: 64 },
      { course: "Law", utmeMin: 180, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 170, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 160, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 150, aggregateHint: 50 }
    ],
  },
  {
    slug: "iau",
    name: "Ibrahim Badamasi Babangida University",
    shortName: "IBBU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Niger",
    seoNote: "IBBU Lapai aggregate and cut-off guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 64 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 50 }
    ],
  },
  {
    slug: "edsu",
    name: "Edo State University",
    shortName: "EDSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Edo",
    seoNote: "EDSU Uzairue aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 240, aggregateHint: 64 },
      { course: "Law", utmeMin: 220, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 50 }
    ],
  },
  {
    slug: "aaau",
    name: "Ambrose Alli University",
    shortName: "AAU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Edo",
    seoNote: "AAU Ekpoma aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 240, aggregateHint: 64 },
      { course: "Law", utmeMin: 220, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 50 }
    ],
  },
  {
    slug: "lau",
    name: "Lead City University",
    shortName: "LCU",
    model: "50-30-20",
    note: "JAMB + screening + O'Level (illustrative)",
    state: "Oyo",
    seoNote: "Lead City University aggregate guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 62 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 52 }
    ],
  },
  {
    slug: "osustech",
    name: "Ondo State University of Science and Technology",
    shortName: "OSUSTECH",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Ondo",
    seoNote: "OSUSTECH Okitipupa aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 200, aggregateHint: 56 },
      { course: "Electrical Engineering", utmeMin: 190, aggregateHint: 54 },
      { course: "Mechanical Engineering", utmeMin: 190, aggregateHint: 54 },
      { course: "Architecture", utmeMin: 180, aggregateHint: 54 },
      { course: "Cyber Security / ICT", utmeMin: 190, aggregateHint: 56 }
    ],
  },
  {
    slug: "bosu",
    name: "Borno State University",
    shortName: "BOSU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Borno",
    seoNote: "BOSU Maiduguri aggregate and cut-off guide.",
    generalUtmeCutoff: 140,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 64 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 180, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 170, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 160, aggregateHint: 50 }
    ],
  },
  {
    slug: "confluence",
    name: "Confluence University of Science and Technology",
    shortName: "CUSTECH",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Kogi",
    seoNote: "CUSTECH Osara aggregate and cut-off guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 200, aggregateHint: 56 },
      { course: "Electrical Engineering", utmeMin: 190, aggregateHint: 54 },
      { course: "Mechanical Engineering", utmeMin: 190, aggregateHint: 54 },
      { course: "Architecture", utmeMin: 180, aggregateHint: 54 },
      { course: "Cyber Security / ICT", utmeMin: 190, aggregateHint: 56 }
    ],
  },
  {
    slug: "uos",
    name: "University of Africa, Toru-Orua",
    shortName: "UAT",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Bayelsa",
    seoNote: "UAT aggregate and cut-off guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 64 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 50 }
    ],
  },
  {
    slug: "ysuk",
    name: "Yusuf Maitama Sule University",
    shortName: "YUMSUK",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Kano",
    seoNote: "YUMSUK Kano aggregate and cut-off guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 64 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 50 }
    ],
  },
  {
    slug: "saau",
    name: "Sa'adu Zungur University",
    shortName: "SAZU",
    model: "50-50",
    note: "JAMB 50% + Post-UTME 50%",
    state: "Bauchi",
    seoNote: "SAZU (formerly BASUG Gadau path) aggregate guide.",
    generalUtmeCutoff: 140,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 64 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 180, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 170, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 160, aggregateHint: 50 }
    ],
  },
  {
    slug: "covenant",
    name: "Covenant University",
    shortName: "Covenant",
    model: "50-30-20",
    note: "JAMB + screening + O'Level (illustrative)",
    state: "Ogun",
    seoNote: "Covenant University aggregate and cut-off guide.",
    generalUtmeCutoff: 200,
    courseCutoffs: [
      { course: "Computer Science", utmeMin: 220, aggregateHint: 65 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 60 },
      { course: "Engineering", utmeMin: 210, aggregateHint: 62 },
      { course: "Architecture", utmeMin: 200, aggregateHint: 60 },
      { course: "Mass Communication", utmeMin: 200, aggregateHint: 58 }
    ],
  },
  {
    slug: "babcock",
    name: "Babcock University",
    shortName: "Babcock",
    model: "50-30-20",
    note: "JAMB + screening + O'Level (illustrative)",
    state: "Ogun",
    seoNote: "Babcock University aggregate and cut-off guide.",
    generalUtmeCutoff: 170,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 240, aggregateHint: 62 },
      { course: "Law", utmeMin: 220, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 52 }
    ],
  },
  {
    slug: "abuad",
    name: "Afe Babalola University",
    shortName: "ABUAD",
    model: "50-30-20",
    note: "JAMB + screening + O'Level (illustrative)",
    state: "Ekiti",
    seoNote: "ABUAD Ado-Ekiti aggregate and cut-off guide.",
    generalUtmeCutoff: 180,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 250, aggregateHint: 62 },
      { course: "Law", utmeMin: 230, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 220, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 210, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 52 }
    ],
  },
  {
    slug: "bowen",
    name: "Bowen University",
    shortName: "Bowen",
    model: "50-30-20",
    note: "JAMB + screening + O'Level (illustrative)",
    state: "Osun",
    seoNote: "Bowen University aggregate and cut-off guide.",
    generalUtmeCutoff: 170,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 62 },
      { course: "Law", utmeMin: 210, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 52 }
    ],
  },
  {
    slug: "landmark",
    name: "Landmark University",
    shortName: "Landmark",
    model: "50-30-20",
    note: "JAMB + screening + O'Level (illustrative)",
    state: "Kwara",
    seoNote: "Landmark University aggregate and cut-off guide.",
    generalUtmeCutoff: 170,
    courseCutoffs: [
      { course: "Agricultural Sciences", utmeMin: 180, aggregateHint: 52 },
      { course: "Engineering", utmeMin: 200, aggregateHint: 58 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 56 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 54 },
      { course: "International Relations", utmeMin: 180, aggregateHint: 52 }
    ],
  },
  {
    slug: "pan-atlantic",
    name: "Pan-Atlantic University",
    shortName: "PAU",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Lagos",
    seoNote: "Pan-Atlantic University aggregate guide.",
    generalUtmeCutoff: 220,
    courseCutoffs: [
      { course: "Business Administration", utmeMin: 200, aggregateHint: 58 },
      { course: "Accounting", utmeMin: 200, aggregateHint: 58 },
      { course: "Media & Communication", utmeMin: 190, aggregateHint: 54 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 56 },
      { course: "Economics", utmeMin: 190, aggregateHint: 54 }
    ],
  },
  {
    slug: "caleb",
    name: "Caleb University",
    shortName: "Caleb",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Lagos",
    seoNote: "Caleb University aggregate and cut-off guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 62 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 52 }
    ],
  },
  {
    slug: "veritas",
    name: "Veritas University",
    shortName: "Veritas",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "FCT",
    seoNote: "Veritas University Abuja aggregate guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 62 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 52 }
    ],
  },
  {
    slug: "nile",
    name: "Nile University of Nigeria",
    shortName: "Nile",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "FCT",
    seoNote: "Nile University Abuja aggregate guide.",
    generalUtmeCutoff: 170,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 62 },
      { course: "Law", utmeMin: 210, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 52 }
    ],
  },
  {
    slug: "baze",
    name: "Baze University",
    shortName: "Baze",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "FCT",
    seoNote: "Baze University Abuja aggregate guide.",
    generalUtmeCutoff: 170,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 62 },
      { course: "Law", utmeMin: 210, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 52 }
    ],
  },
  {
    slug: "ajayi",
    name: "Ajayi Crowther University",
    shortName: "ACU",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Oyo",
    seoNote: "Ajayi Crowther University aggregate guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 62 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 52 }
    ],
  },
  {
    slug: "redeemer",
    name: "Redeemer's University",
    shortName: "RUN",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Osun",
    seoNote: "Redeemer's University aggregate guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 62 },
      { course: "Law", utmeMin: 210, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 52 }
    ],
  },
  {
    slug: "madonna",
    name: "Madonna University",
    shortName: "Madonna",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Anambra",
    seoNote: "Madonna University aggregate guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 230, aggregateHint: 62 },
      { course: "Law", utmeMin: 210, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 52 }
    ],
  },
  {
    slug: "igbinedion",
    name: "Igbinedion University",
    shortName: "IUO",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Edo",
    seoNote: "Igbinedion University Okada aggregate guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 240, aggregateHint: 62 },
      { course: "Law", utmeMin: 220, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 210, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 200, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 190, aggregateHint: 52 }
    ],
  },
  {
    slug: "benson",
    name: "Benson Idahosa University",
    shortName: "BIU",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Edo",
    seoNote: "Benson Idahosa University aggregate guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 62 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 52 }
    ],
  },
  {
    slug: "crawford",
    name: "Crawford University",
    shortName: "Crawford",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Ogun",
    seoNote: "Crawford University aggregate guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 62 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 52 }
    ],
  },
  {
    slug: "mountain-top",
    name: "Mountain Top University",
    shortName: "MTU",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Ogun",
    seoNote: "Mountain Top University aggregate guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 62 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 52 }
    ],
  },
  {
    slug: "chrisland",
    name: "Chrisland University",
    shortName: "Chrisland",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Ogun",
    seoNote: "Chrisland University aggregate guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 62 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 52 }
    ],
  },
  {
    slug: "adeleke",
    name: "Adeleke University",
    shortName: "Adeleke",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Osun",
    seoNote: "Adeleke University aggregate guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 62 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 52 }
    ],
  },
  {
    slug: "gregory",
    name: "Gregory University",
    shortName: "Gregory",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Abia",
    seoNote: "Gregory University Uturu aggregate guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 62 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 52 }
    ],
  },
  {
    slug: "godfrey",
    name: "Godfrey Okoye University",
    shortName: "GOUNI",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Enugu",
    seoNote: "Godfrey Okoye University aggregate guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 62 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 52 }
    ],
  },
  {
    slug: "caritas",
    name: "Caritas University",
    shortName: "Caritas",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Enugu",
    seoNote: "Caritas University aggregate guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 62 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 52 }
    ],
  },
  {
    slug: "novena",
    name: "Novena University",
    shortName: "Novena",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Delta",
    seoNote: "Novena University aggregate guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 62 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 52 }
    ],
  },
  {
    slug: "western-delta",
    name: "Western Delta University",
    shortName: "WDU",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Delta",
    seoNote: "Western Delta University aggregate guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 62 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 52 }
    ],
  },
  {
    slug: "achievers",
    name: "Achievers University",
    shortName: "Achievers",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Ondo",
    seoNote: "Achievers University Owo aggregate guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 62 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 52 }
    ],
  },
  {
    slug: "elizade",
    name: "Elizade University",
    shortName: "Elizade",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Ondo",
    seoNote: "Elizade University aggregate guide.",
    generalUtmeCutoff: 160,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 62 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 52 }
    ],
  },
  {
    slug: "kings",
    name: "Kings University",
    shortName: "Kings",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Osun",
    seoNote: "Kings University Odeomu aggregate guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 62 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 52 }
    ],
  },
  {
    slug: "fountain",
    name: "Fountain University",
    shortName: "Fountain",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Osun",
    seoNote: "Fountain University Osogbo aggregate guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 62 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 52 }
    ],
  },
  {
    slug: "al-hikmah",
    name: "Al-Hikmah University",
    shortName: "Al-Hikmah",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Kwara",
    seoNote: "Al-Hikmah University Ilorin aggregate guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 220, aggregateHint: 62 },
      { course: "Law", utmeMin: 200, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 200, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 190, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 180, aggregateHint: 52 }
    ],
  },
  {
    slug: "summit",
    name: "Summit University",
    shortName: "Summit",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Kwara",
    seoNote: "Summit University Offa aggregate guide.",
    generalUtmeCutoff: 140,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 200, aggregateHint: 62 },
      { course: "Law", utmeMin: 180, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 180, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 170, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 160, aggregateHint: 52 }
    ],
  },
  {
    slug: "mcpherson",
    name: "McPherson University",
    shortName: "McPherson",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Ogun",
    seoNote: "McPherson University aggregate guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 62 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 52 }
    ],
  },
  {
    slug: "christopher",
    name: "Christopher University",
    shortName: "Christopher",
    model: "50-30-20",
    note: "JAMB + screening (illustrative)",
    state: "Ogun",
    seoNote: "Christopher University aggregate guide.",
    generalUtmeCutoff: 150,
    courseCutoffs: [
      { course: "Medicine & Surgery", utmeMin: 210, aggregateHint: 62 },
      { course: "Law", utmeMin: 190, aggregateHint: 58 },
      { course: "Nursing", utmeMin: 190, aggregateHint: 56 },
      { course: "Computer Science", utmeMin: 180, aggregateHint: 54 },
      { course: "Accounting", utmeMin: 170, aggregateHint: 52 }
    ],
  },
];

export const universityMap = Object.fromEntries(universities.map((u) => [u.slug, u]));

export function getUniversity(slug: string) {
  return universityMap[slug] ?? null;
}
